PRODUCTS = [
    {
        "slug": "education",
        "name": "Education",
        "shortDescription": "Institutes, classes, assignments, and student reports",
        "iconUrl": "/icons/education.svg",
        "category": "learning",
        "tags": ["schools", "teachers", "students"],
        "featured": True,
        "launchUrl": "http://localhost:3010",
    },
    {
        "slug": "social",
        "name": "Social",
        "shortDescription": "Feed, connections, and family relationship graphs",
        "iconUrl": "/icons/social.svg",
        "category": "community",
        "tags": ["feed", "relationships"],
        "featured": True,
        "launchUrl": "http://localhost:3020",
    },
    {
        "slug": "analytics",
        "name": "Analytics",
        "shortDescription": "Cross-product insights and usage dashboards",
        "iconUrl": "/icons/analytics.svg",
        "category": "business",
        "tags": ["reports", "metrics"],
        "featured": False,
        "launchUrl": "http://localhost:3030",
    },
    {
        "slug": "calendar",
        "name": "Calendar",
        "shortDescription": "Shared scheduling across institute and family",
        "iconUrl": "/icons/calendar.svg",
        "category": "productivity",
        "tags": ["events", "scheduling"],
        "featured": False,
        "launchUrl": "http://localhost:3040",
    },
    {
        "slug": "messaging",
        "name": "Messaging",
        "shortDescription": "Secure messaging for teachers, parents, and staff",
        "iconUrl": "/icons/messaging.svg",
        "category": "communication",
        "tags": ["chat", "notifications"],
        "featured": True,
        "launchUrl": "http://localhost:3050",
    },
    {
        "slug": "billing",
        "name": "Billing",
        "shortDescription": "Invoices and subscription management for institutes",
        "iconUrl": "/icons/billing.svg",
        "category": "business",
        "tags": ["payments", "invoices"],
        "featured": False,
        "launchUrl": "http://localhost:3060",
    },
    {
        "slug": "library",
        "name": "Library",
        "shortDescription": "Digital resources and reading lists for students",
        "iconUrl": "/icons/library.svg",
        "category": "learning",
        "tags": ["books", "resources"],
        "featured": False,
        "launchUrl": "http://localhost:3070",
    },
    {
        "slug": "wellness",
        "name": "Wellness",
        "shortDescription": "Student wellbeing check-ins and counselor tools",
        "iconUrl": "/icons/wellness.svg",
        "category": "health",
        "tags": ["wellbeing", "counseling"],
        "featured": False,
        "launchUrl": "http://localhost:3080",
    },
    {
        "slug": "events",
        "name": "Events",
        "shortDescription": "School events, RSVPs, and volunteer coordination",
        "iconUrl": "/icons/events.svg",
        "category": "community",
        "tags": ["rsvp", "volunteers"],
        "featured": False,
        "launchUrl": "http://localhost:3090",
    },
    {
        "slug": "forms",
        "name": "Forms",
        "shortDescription": "Permission slips, surveys, and digital form collection",
        "iconUrl": "/icons/forms.svg",
        "category": "productivity",
        "tags": ["surveys", "permissions"],
        "featured": False,
        "launchUrl": "http://localhost:3100",
    },
]
